<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Modules\Settings\App\Models\Module;
use Modules\Settings\App\Models\Page;
use Modules\Settings\App\Models\PageAction;
use Modules\Settings\App\Models\Role;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $module_dashboard = Module::create([
            'name_en' => 'Dashboard',
            'name_kh' => 'ផ្ទាំងគ្រប់គ្រង',
            'slug' => 'dashboard',
            'icon' => 'icon-home',
            'active' => 'Y',
            'order' => 1,
        ])->id;
        $page_dashboard = Page::create([
            'module_id' => $module_dashboard,
            'name_en' => 'Dashboard',
            'name_kh' => 'ផ្ទាំងគ្រប់គ្រង',
            'slug' => 'dashboard',
            'icon' => 'icon-home',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 1,
        ])->id;
        $page_action_dashboard = PageAction::insert([
            [
                'page_id' => $page_dashboard,
                'name_en' => 'Dashboard',
                'name_kh' => 'ផ្ទាំងគ្រប់គ្រង',
                'route_name' => 'dashboard.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'icon-home',
                'active' => 'Y',
                'is_param' => 'N',
                'params' => null,
            ],
        ]);
        $module = Module::create([
            'name_en' => 'Settings',
            'name_kh' => 'ការកំណត់',
            'slug' => 'settings',
            'icon' => 'fas fa-cogs',
            'active' => 'Y',
            'order' => 2,
        ])->id;
        $page_module = Page::create([
            'module_id' => $module,
            'name_en' => 'Modules',
            'name_kh' => 'កំណត់ម៉ូដ្យួល',
            'slug' => 'module',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 1,
        ])->id;
        $page_of_module = PageAction::insert([
            [
                'page_id' => $page_module,
                'name_en' => 'Module',
                'name_kh' => 'ម៉ូដ្យួល',
                'route_name' => 'settings.module.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.module.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.module.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Generate',
                'name_kh' => 'បង្កើតថត',
                'route_name' => 'settings.module.generate',
                'type' => 'generate',
                'position' => 'action',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.module.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.module.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_module,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.module.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'Y',
            ],
        ]);

        // Create Page of Pages With Page_actions
        $page_page = Page::create([
            'module_id' => $module,
            'name_en' => 'Pages',
            'name_kh' => 'កំណត់ទំព័រ',
            'slug' => 'page',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 2,
        ])->id;
        $page_of_Pages = PageAction::insert([
            [
                'page_id' => $page_page,
                'name_en' => 'Pages',
                'name_kh' => 'ទំព័រ',
                'route_name' => 'settings.page.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_page,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.page.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_page,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.page.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_page,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.page.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_page,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.page.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_page,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.page.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'Y',
            ],
        ]);

        // Create Page role With Page_actions
        $page_role = Page::create([
            'module_id' => $module,
            'name_en' => 'Roles',
            'name_kh' => 'ក្រុមអ្នកប្រើប្រាស់',
            'slug' => 'role',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 3,
        ])->id;
        $page_of_role = PageAction::insert([
            [
                'page_id' => $page_role,
                'name_en' => 'role',
                'name_kh' => 'ក្រុមអ្នកប្រើប្រាស់',
                'route_name' => 'settings.role.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_role,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.role.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_role,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.role.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_role,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.role.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_role,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.role.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_role,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.role.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'Y',
            ],
        ]);

        // Create Page user With Page_actions
        $page_user = Page::create([
            'module_id' => $module,
            'name_en' => 'Users',
            'name_kh' => 'អ្នកប្រើប្រាស់',
            'slug' => 'user',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 4,
        ])->id;
        $page_of_user = PageAction::insert([
            [
                'page_id' => $page_user,
                'name_en' => 'User',
                'name_kh' => 'អ្នកប្រើប្រាស់',
                'route_name' => 'settings.user.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.user.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Change Password',
                'name_kh' => 'ផ្លាស់ប្តូពាក្យសម្ងាត់',
                'route_name' => 'settings.user.changePassword',
                'type' => 'changePassword',
                'position' => 'action',
                'icon' => 'fas fa-user-lock',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.user.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.user.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.user.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $page_user,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.user.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'Y',
            ],
        ]);

        // Create Page locale With Page_actions
        $locale_page = Page::create([
            'module_id' => $module,
            'name_en' => 'Localization',
            'name_kh' => 'កំណត់ភាសា',
            'slug' => 'locale',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 5,
        ])->id;
        $locale_of_page = PageAction::insert([
            [
                'page_id' => $locale_page,
                'name_en' => 'Localization',
                'name_kh' => 'កំណត់ភាសា',
                'route_name' => 'settings.locale.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $locale_page,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.locale.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $locale_page,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.locale.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $locale_page,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.locale.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $locale_page,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.locale.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $locale_page,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.locale.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'N',
            ],
        ]);

        // Create Page locale With Page_actions
        $translation_page = Page::create([
            'module_id' => $module,
            'name_en' => 'Translations',
            'name_kh' => 'ការបកប្រែ',
            'slug' => 'translation',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 6,
        ])->id;
        $translation_of_page = PageAction::insert([
            [
                'page_id' => $translation_page,
                'name_en' => 'Translations',
                'name_kh' => 'ការបកប្រែ',
                'route_name' => 'settings.translation.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.translation.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.translation.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.translation.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.translation.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.translation.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'N',
            ],
            [
                'page_id' => $translation_page,
                'name_en' => 'Sync',
                'name_kh' => 'ធ្វើបច្ចុប្បន្នភាព',
                'route_name' => 'settings.translation.sync',
                'type' => 'sync',
                'position' => 'other',
                'icon' => 'fas fa-sync',
                'active' => 'Y',
            ],
        ]);

        // Create Page locale With Page_actions
        $configuration_page = Page::create([
            'module_id' => $module,
            'name_en' => 'Configuration',
            'name_kh' => 'ការកំណត់រចនាសម្ព័ន្ធ',
            'slug' => 'configuration',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 7,
        ])->id;
        $configuration_of_page = PageAction::insert([
            [
                'page_id' => $configuration_page,
                'name_en' => 'Configuration',
                'name_kh' => 'ការកំណត់រចនាសម្ព័ន្ធ',
                'route_name' => 'settings.configuration.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.configuration.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Edit',
                'name_kh' => 'កែប្រែ',
                'route_name' => 'settings.configuration.edit',
                'type' => 'edit',
                'position' => 'action',
                'icon' => 'fas fa-edit',
                'active' => 'Y',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.configuration.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Restore',
                'name_kh' => 'ស្តារ',
                'route_name' => 'settings.configuration.restore',
                'type' => 'restore',
                'position' => 'action',
                'icon' => 'fas fa-undo',
                'active' => 'Y',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Export',
                'name_kh' => 'នាំចេញ',
                'route_name' => 'settings.configuration.export',
                'type' => 'exported',
                'position' => 'other',
                'icon' => 'fas fa-download',
                'active' => 'N',
            ],
            [
                'page_id' => $configuration_page,
                'name_en' => 'Sync',
                'name_kh' => 'ធ្វើបច្ចុប្បន្នភាព',
                'route_name' => 'settings.configuration.sync',
                'type' => 'sync',
                'position' => 'other',
                'icon' => 'fas fa-sync',
                'active' => 'Y',
            ],
        ]);

        // Create Page Backup With Page_actions
        $backup_page = Page::create([
            'module_id' => $module,
            'name_en' => 'Backup',
            'name_kh' => 'បម្រុងទុក',
            'slug' => 'backup',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'N',
            'order' => 8,
        ])->id;
        $backup_page_actions = PageAction::insert([
            [
                'page_id' => $backup_page,
                'name_en' => 'Backups',
                'name_kh' => 'បម្រុងទុក',
                'route_name' => 'settings.backup.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
            [
                'page_id' => $backup_page,
                'name_en' => 'Create',
                'name_kh' => 'បង្កើត',
                'route_name' => 'settings.backup.create',
                'type' => 'create',
                'position' => 'top',
                'icon' => 'fas fa-plus-circle',
                'active' => 'Y',
            ],
            [
                'page_id' => $backup_page,
                'name_en' => 'Delete',
                'name_kh' => 'លុប',
                'route_name' => 'settings.backup.destroy',
                'type' => 'destroy',
                'position' => 'action',
                'icon' => 'fas fa-trash',
                'active' => 'Y',
            ],
            [
                'page_id' => $backup_page,
                'name_en' => 'Download',
                'name_kh' => 'ទាញយក',
                'route_name' => 'settings.backup.download',
                'type' => 'download',
                'position' => 'action',
                'icon' => 'fas fa-download',
                'active' => 'Y',
            ],
        ]);

        // Create Page Systemlog With Page_actions
        $page_systemlog = Page::create([
            'module_id' => $module,
            'name_en' => 'Activity Log',
            'name_kh' => 'តាមដានការប្រើប្រាស់',
            'slug' => 'system-user-log',
            'icon' => 'far fa-folder',
            'default_action' => 'index',
            'active' => 'Y',
            'order' => 9,
        ])->id;
        $page_of_systemlog = PageAction::insert([
            [
                'page_id' => $page_systemlog,
                'name_en' => 'Activity Log',
                'name_kh' => 'តាមដានអ្នកប្រើប្រាស់ប្រព័ន្ធ',
                'route_name' => 'settings.systemlog.index',
                'type' => 'index',
                'position' => null,
                'icon' => 'far fa-folder',
                'active' => 'Y',
            ],
        ]);
    }
}
