<?php

return [
    'datatable_card' => 'table text-nowrap datatables no-footer',
    'date_format' => 'd-M-Y',
    'time_format' => 'H:i A',
    'datetime_format' => 'd-M-Y H:i A',
    'datetime_format_24h' => 'd-M-Y H:i:s',
    'time_start' => '00:00:00',
    'time_end' => '23:59:59',
    'disk_name' => 'public_upload',
    'upload_path' => 'uploads/',
    'upload_lang_path' => '/lang',
    'image_default_value' => 'no-avatar.png',
    'form_group_class' => 'form-group row align-items-center',
    'form_label_class' => 'col-sm-2 col-form-label text-end',
    'form_div_input_class' => 'col-sm-10',
    'form_input_class' => 'form-control',
    'button_search_class' => 'btn btn-primary',
    'button_back_class' => 'btn btn-danger',
    'button_save_class' => 'btn btn-primary',
    'button_save_new_class' => 'btn btn-info',
    'icon_save' => 'fas fa-save',
    'icon_save_new' => 'fas fa-save',
    'icon_back' => 'fas fa-arrow-left',
    'badge_count' => 'badge badge-count',
    'badge_success' => 'badge badge-success',
    'badge_danger' => 'badge badge-danger',
    'badge_warning' => 'badge badge-warning',
    'badge_info' => 'badge badge-info',
    'badge_primary' => 'badge badge-primary',
    'badge_default' => 'badge badge-black',
    'upload_width' => 200,
    'upload_height' => 200,
    'lang_width' => 256,
    'lang_height' => 164,
    'lang_quality' => 100,
    'avatar_width' => 1024,
    'avatar_height' => 1024,
    'avatar_quality' => 100,
    'upload_max_size' => 5242880,
];
